export const THIRD_PERSON_SUBJECTS = [
  { display: 'lui',            gender: 'male',              number: 'singular', register: null       },
  { display: 'lei',            gender: 'female',            number: 'singular', register: null       },
  { display: 'loro',           gender: ['male', 'female'],  number: 'plural',   register: null       },
  { display: 'voi',            gender: ['male', 'female'],  number: 'plural',   register: null       },
  { display: 'Mario',          gender: 'male',              number: 'singular', register: null       },
  { display: 'Giulio',         gender: 'male',              number: 'singular', register: null       },
  { display: 'Maria',          gender: 'female',            number: 'singular', register: null       },
  { display: 'Giulia',         gender: 'female',            number: 'singular', register: null       },
  { display: 'Mario e Giulio', gender: 'male',              number: 'plural',   register: null       },
  { display: 'Maria e Giulia', gender: 'female',            number: 'plural',   register: null       },
  { display: 'egli',           gender: 'male',              number: 'singular', register: 'literary' },
  { display: 'esso',           gender: 'male',              number: 'singular', register: 'literary' },
  { display: 'ella',           gender: 'female',            number: 'singular', register: 'literary' },
  { display: 'essa',           gender: 'female',            number: 'singular', register: 'literary' },
  { display: 'essi',           gender: 'male',              number: 'plural',   register: 'literary' },
  { display: 'esse',           gender: 'female',            number: 'plural',   register: 'literary' },
  { display: 'Loro',           gender: ['male', 'female'],  number: 'plural',   register: 'formal'   },
];
