export const TENSES = {
  presente: {
    label: '直説法現在',
    italian: 'Indicativo Presente',
    description: '',
    type: 'simple',
    mood: 'indicative',
    timeframe: 'present',
  },
  passatoProssimo: {
    label: '直説法近過去',
    italian: 'Indicativo Passato Prossimo',
    description: '',
    type: 'compound',
    mood: 'indicative',
    timeframe: 'past',
  },
  imperfetto: {
    label: '直説法半過去',
    italian: 'Indicativo Imperfetto',
    description: '',
    type: 'simple',
    mood: 'indicative',
    timeframe: 'past',
  },
  passatoRemoto: {
    label: '直説法遠過去',
    italian: 'Indicativo Passato Remoto',
    description: '',
    type: 'simple',
    mood: 'indicative',
    timeframe: 'past',
  },
  trapassatoProssimo: {
    label: '直説法大過去',
    italian: 'Indicativo Trapassato Prossimo',
    description: '',
    type: 'compound',
    mood: 'indicative',
    timeframe: 'past',
  },
  trapassatoRemoto: {
    label: '直説法先立過去',
    italian: 'Indicativo Trapassato Remoto',
    description: '',
    type: 'compound',
    mood: 'indicative',
    timeframe: 'past',
  },
  futuroSemplice: {
    label: '直説法単純未来',
    italian: 'Indicativo Futuro Semplice',
    description: '',
    type: 'simple',
    mood: 'indicative',
    timeframe: 'future',
  },
  futuroAnteriore: {
    label: '直説法先立未来',
    italian: 'Indicativo Futuro Anteriore',
    description: '',
    type: 'compound',
    mood: 'indicative',
    timeframe: 'future',
  },
  congiuntivoPresente: {
    label: '接続法現在',
    italian: 'Congiuntivo Presente',
    description: '',
    type: 'simple',
    mood: 'subjunctive',
    timeframe: 'present',
  },
  congiuntivoPassato: {
    label: '接続法過去',
    italian: 'Congiuntivo Passato',
    description: '',
    type: 'compound',
    mood: 'subjunctive',
    timeframe: 'past',
  },
  congiuntivoImperfetto: {
    label: '接続法半過去',
    italian: 'Congiuntivo Imperfetto',
    description: '',
    type: 'simple',
    mood: 'subjunctive',
    timeframe: 'past',
  },
  congiuntivoTrapassato: {
    label: '接続法大過去',
    italian: 'Congiuntivo Trapassato',
    description: '',
    type: 'compound',
    mood: 'subjunctive',
    timeframe: 'past',
  },
  condizionalePresente: {
    label: '条件法現在',
    italian: 'Condizionale Presente',
    description: '',
    type: 'simple',
    mood: 'conditional',
    timeframe: 'present',
  },
  condizionalePassato: {
    label: '条件法過去',
    italian: 'Condizionale Passato',
    description: '',
    type: 'compound',
    mood: 'conditional',
    timeframe: 'past',
  },
  imperativo: {
    label: '命令法（現在）',
    italian: 'Imperativo Presente',
    description: '',
    type: 'simple',
    mood: 'imperative',
    timeframe: 'present',
  },
  infinito: {
    label: '不定詞',
    italian: 'Infinito',
    description: '',
    type: 'simple',
    mood: 'nonfinite',
    timeframe: 'nonfinite',
  },
  participio: {
    label: '分詞',
    italian: 'Participio',
    description: '',
    type: 'simple',
    mood: 'nonfinite',
    timeframe: 'nonfinite',
  },
  gerundio: {
    label: 'ジェルンディオ',
    italian: 'Gerundio',
    description: '',
    type: 'simple',
    mood: 'nonfinite',
    timeframe: 'nonfinite',
  },
};

export const MOOD_LABELS = {
  indicative: '直説法',
  subjunctive: '接続法',
  conditional: '条件法',
  imperative: '命令法',
};

export const TIMEFRAME_LABELS = {
  present: '現在',
  past: '過去',
  future: '未来',
};
